/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu;

import entidad.Juego;
import javax.swing.JLabel;
import servicios.JuegoServicio;

/**
 *
 * @author User
 */
public class Pantalla extends javax.swing.JFrame {

    JuegoServicio serv = new JuegoServicio();
    Juego j1 = serv.crearJuego();
    

    public void mostrar() {
        buttonReiniciar.setEnabled(false);
        //System.err.println("La palabra secreta es " + j1.getMesSecreto());
    }

//    public void activarButton(){
//   if (label_resultado.getText().equalsIgnoreCase("Felicidades has Adivinado")){
//         
//    
//    }else{}
//
//
//}
    
    
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tituklo = new javax.swing.JLabel();
        textAdivina = new javax.swing.JTextField();
        buttonProbar = new javax.swing.JButton();
        buttonBorrar = new javax.swing.JButton();
        buttonReiniciar = new javax.swing.JButton();
        label_resultado = new javax.swing.JLabel();
        buttonPista = new javax.swing.JButton();
        labelPista = new javax.swing.JLabel();
        labelGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tituklo.setFont(new java.awt.Font("Alien Encounters Solid", 1, 24)); // NOI18N
        Tituklo.setText("Adivina el Mes");

        textAdivina.setText("Mes");
        textAdivina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAdivinaActionPerformed(evt);
            }
        });

        buttonProbar.setText("Probar");
        buttonProbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProbarActionPerformed(evt);
            }
        });

        buttonBorrar.setText("Borrar");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        buttonReiniciar.setText("Reiniciar");
        buttonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReiniciarActionPerformed(evt);
            }
        });

        label_resultado.setFont(new java.awt.Font("CreativeBlock BB", 1, 18)); // NOI18N
        label_resultado.setForeground(new java.awt.Color(255, 0, 0));

        buttonPista.setText("Pista");
        buttonPista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPistaMouseClicked(evt);
            }
        });
        buttonPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPistaActionPerformed(evt);
            }
        });

        labelPista.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        labelGanador.setBackground(new java.awt.Color(0, 0, 0));
        labelGanador.setFont(new java.awt.Font("Zootopia JPosters.com.ar", 0, 18)); // NOI18N
        labelGanador.setForeground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Tituklo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(textAdivina, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(buttonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonProbar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonReiniciar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(labelPista, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Tituklo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textAdivina, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBorrar)
                    .addComponent(buttonProbar)
                    .addComponent(buttonReiniciar)
                    .addComponent(buttonPista))
                .addGap(18, 18, 18)
                .addComponent(labelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProbarActionPerformed
        //evento del botonProbar
       // System.out.println(j1.getMesSecreto());
        String adiv=textAdivina.getText();
        j1.setAdivina(adiv);//guardando el valor de texto adivina en la variable
        //System.out.println(j1.getAdivina());
        metodoResultado();
//serv.adivinarMesPanta(j1);
      
//        if (cont > 0) {
//            activarButton();
//        }

    }//GEN-LAST:event_buttonProbarActionPerformed
private void metodoResultado(){
     if (j1.getAdivina().equalsIgnoreCase(j1.getMesSecreto())) {
            labelGanador.setText("Felicidades has Adivinado");
         buttonReiniciar.setEnabled(true); 
        } else {
            label_resultado.setText("Respuesta Incorrecta");
            buttonReiniciar.setEnabled(false);
        }
    
}
    private void textAdivinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAdivinaActionPerformed


    }//GEN-LAST:event_textAdivinaActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        textAdivina.setText("");///borra el texto antes ingresado
        label_resultado.setText("");//borra el msj del resultado
        this.textAdivina.requestFocus();
    }//GEN-LAST:event_buttonBorrarActionPerformed

    private void buttonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReiniciarActionPerformed
        Juego j1 = serv.crearJuego();
        
        labelPista.setText("");
        label_resultado.setText("");
        labelGanador.setText("");
        buttonPista.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReiniciarActionPerformed

    private void buttonPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPistaActionPerformed
         char pista= j1.getMesSecreto().charAt((j1.getMesSecreto().length()-1));
        labelPista.setText("Pista: El mes termina con la letra "+pista);

       
    }//GEN-LAST:event_buttonPistaActionPerformed

    private void buttonPistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPistaMouseClicked
        buttonPista.setEnabled(false);
    }//GEN-LAST:event_buttonPistaMouseClicked

    public JLabel getLabel_resultado() {
        return label_resultado;
    }

    public void setLabel_resultado(JLabel label_resultado) {
        this.label_resultado = label_resultado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tituklo;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonPista;
    private javax.swing.JButton buttonProbar;
    private javax.swing.JButton buttonReiniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelGanador;
    private javax.swing.JLabel labelPista;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JTextField textAdivina;
    // End of variables declaration//GEN-END:variables
}
